routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/','BookController@index');
Route::group(['middleware' => 'auth' ], function(){
    Route::get('/', [
        'as' => 'home', 'uses' => 'PagesController@index'
    ]);
});
Route::get('/category', 'BookController@category');

Route::resource('/book','BookController');
Route::post('/book/borrow/{id}', 'BookController@borrow');
Route::post('/book/return/{id}', 'BookController@return');


Route::resource('/project','ProjectsController');
Route::resource('/project/project-item','ProjectItemsController');
Route::get('/projectitem/filtered/',[
    'as'   => 'project.showItemFiltered',
    'uses' => 'ProjectItemsController@filter']);
//start={start}&end={end}&type={type}&status={status}

Route::get('/project/project-item/{id}/approve','ProjectItemsController@approve');
Route::get('/project/project-item/{id}/decline','ProjectItemsController@decline');
Route::post('/project/adduser/{project_id}&{user_id}','ProjectsController@add_user');
Route::post('/project/removeuser/{project_id}&{user_id}','ProjectsController@remove_user');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index');

resources/views/inc/mainnav.blade.php
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
    <div class="container">
       <div class="col-12">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{config('app.name','wishvisit')}}
            </a>
        </div>
        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
               <li><a href="{{ route('project.showItemFiltered') }}">Filtered request</a></li>
               <li><a href="{{ route('project.create') }}">Create New Project</a></li>
            </ul>
            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @guest
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                @else
                    <style type="text/css">
                        .dropdown:hover .dropdown-menu{display: block;}
                    </style>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                            {{ Auth::user()->name }} 
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="/dashboard">Dashboard</a>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endguest
            </ul>
        </div>
    	</div>
    </div>
</nav>

resources/views/inc/messages.blade.php
@if($errors)

	@foreach($errors->all() as $error)
		<div class="alert alert-danger">
			{{$error}}
		</div>
	@endforeach
@endif

@if(session('success'))
	<div class="alert alert-success">
		{{session('success')}}
	</div>
@endif

@if(session('error'))
	<div class="alert alert-danger">
		{{session('error')}}
	</div>
@endif